"""create email and related tables

Revision ID: 104ea2a408c6
Revises: 620e8e233949
Create Date: 2025-07-15 15:48:31.092159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104ea2a408c6'
down_revision: Union[str, Sequence[str], None] = '620e8e233949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('admin_mail_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender_mail_id', sa.String(), nullable=True),
    sa.Column('revicer_mail_id', sa.String(), nullable=True),
    sa.Column('cc_reciver_mail_id', sa.String(), nullable=True),
    sa.Column('bcc_reciver_mail_id', sa.String(), nullable=True),
    sa.Column('content_encoding', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('datetime_format', sa.DateTime(), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.Column('has_thread', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=True),
    sa.Column('thread_index', sa.String(), nullable=True),
    sa.Column('references', sa.String(), nullable=True),
    sa.Column('in_reply_to', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender_mail_id', sa.String(), nullable=True),
    sa.Column('revicer_mail_id', sa.String(), nullable=True),
    sa.Column('cc_reciver_mail_id', sa.String(), nullable=True),
    sa.Column('bcc_reciver_mail_id', sa.String(), nullable=True),
    sa.Column('content_encoding', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('datetime_format', sa.DateTime(), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('doc_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('threads')
    op.drop_table('emails')
    # ### end Alembic commands ###
