"""Add ms_graph_id to Email

Revision ID: 825672def48a
Revises: 104ea2a408c6
Create Date: 2025-07-16 14:48:31.431349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825672def48a'
down_revision: Union[str, Sequence[str], None] = '104ea2a408c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('ms_graph_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_emails_ms_graph_id'), 'emails', ['ms_graph_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_ms_graph_id'), table_name='emails')
    op.drop_column('emails', 'ms_graph_id')
    # ### end Alembic commands ###
